"""empty message

Revision ID: 5baaafa47739
Revises: 
Create Date: 2026-02-11 01:09:29.107234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5baaafa47739'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('specialty', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phonenumber', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('doctor_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=25), nullable=False),
    sa.Column('last_name', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phonenumber', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('password_reset',
    sa.Column('reset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('reset_id')
    )
    op.create_table('pets',
    sa.Column('pet_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('pet_type', sa.String(length=30), nullable=False),
    sa.Column('birthdate', sa.String(length=50), nullable=True),
    sa.Column('breed', sa.String(length=120), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('allergies', sa.String(length=255), nullable=True),
    sa.Column('neutered', sa.Boolean(), nullable=False),
    sa.Column('info', sa.String(length=500), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('pet_id')
    )
    op.create_table('appointments',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('time', sa.String(length=50), nullable=False),
    sa.Column('motive', sa.String(length=250), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('anamnesis', sa.String(length=500), nullable=True),
    sa.Column('procedures', sa.String(length=500), nullable=True),
    sa.Column('medication', sa.String(length=500), nullable=True),
    sa.Column('observations', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.pet_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_table('vaccines',
    sa.Column('vaccine_id', sa.Integer(), nullable=False),
    sa.Column('vaccine_name', sa.String(length=20), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('vaccination_date', sa.String(length=20), nullable=False),
    sa.Column('expiry_date', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.pet_id'], ),
    sa.PrimaryKeyConstraint('vaccine_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaccines')
    op.drop_table('appointments')
    op.drop_table('pets')
    op.drop_table('password_reset')
    op.drop_table('users')
    op.drop_table('doctors')
    # ### end Alembic commands ###
